version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - EduardoGHdez
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
